Add latest changes from gitlab-org/gitlab@master

diff --git a/lib/gitlab/ci/templates/Jobs/Secret-Detection.gitlab-ci.yml b/lib/gitlab/ci/templates/Jobs/Secret-Detection.gitlab-ci.yml
--- a/lib/gitlab/ci/templates/Jobs/Secret-Detection.gitlab-ci.yml
+++ b/lib/gitlab/ci/templates/Jobs/Secret-Detection.gitlab-ci.yml
@@ -50,11 +50,8 @@ secret_detection:
         git fetch --depth=2 origin $CI_COMMIT_REF_NAME
       else
         # determine commit range so that we can fetch the appropriate depth
-        set +e # ignore exit on failure
-        git log --no-merges --pretty=format:"%H" ${CI_COMMIT_BEFORE_SHA}..${CI_COMMIT_SHA} >${CI_COMMIT_SHA}_commit_list.txt
-
-        # check the exit code of the previous command to determine if we need to limit the commit_list.txt to CI_COMMIT_SHA.
-        if [ $? -ne 0 ];
+        # check the exit code to determine if we need to limit the commit_list.txt to CI_COMMIT_SHA.
+        if ! git log --no-merges --pretty=format:"%H" ${CI_COMMIT_BEFORE_SHA}..${CI_COMMIT_SHA} >${CI_COMMIT_SHA}_commit_list.txt;
         then
           echo "unable to determine commit range, limiting to ${CI_COMMIT_SHA}"
           echo ${CI_COMMIT_SHA} >${CI_COMMIT_SHA}_commit_list.txt
@@ -63,9 +60,6 @@ secret_detection:
           # newline, this is to keep the log messages consistent
           echo >> ${CI_COMMIT_SHA}_commit_list.txt
         fi
-
-        # re-enable exit on failure
-        set -e
 
         # we need to extend the git fetch depth to the number of commits + 1 for the following reasons:
         # to include the parent commit of the base commit in this MR/Push event. This is needed because
