Add latest changes from gitlab-org/gitlab@master

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -162,6 +162,38 @@ pre-commit:
     secrets-detection:
       tags: secrets
       run: .lefthook/gitleaks.sh pre-commit
+    docs-metadata: # See https://docs.gitlab.com/ee/development/documentation/metadata.html
+      tags: documentation style
+      files: git diff --name-only --diff-filter=d --staged
+      glob: 'doc/*.md'
+      run: scripts/lint-docs-metadata.sh {files}
+    docs-deprecations:
+      tags: documentation
+      files: git diff --name-only --diff-filter=d --staged
+      glob: 'data/deprecations/*.yml'
+      run: echo "Changes to deprecation files detected. Checking deprecations..\n"; bundle exec rake gitlab:docs:check_deprecations
+    docs-link-check:
+      tags: documentation
+      files: git diff --name-only --diff-filter=d --staged
+      glob: 'doc/*.md'
+      run: scripts/lint-docs-link-check.sh
+    markdownlint:
+      tags: documentation style
+      files: git diff --name-only --diff-filter=d --staged
+      exclude: 'doc/api/graphql/reference/index.md'
+      glob: 'doc/*.md'
+      run: yarn markdownlint {files}
+    mermaidlint:
+      tags: documentation style,backend style,frontend style
+      files: git diff --name-only --diff-filter=d --staged
+      glob: '{app,lib,ee,spec,doc,scripts}/**/*.md'
+      run: scripts/lint/check_mermaid.mjs {files}
+    vale: # Requires Vale: https://docs.gitlab.com/ee/development/documentation/testing/vale.html
+      tags: documentation style
+      files: git diff --name-only --diff-filter=d --staged
+      exclude: 'doc/api/graphql/reference/index.md'
+      glob: 'doc/*.md'
+      run: 'if [ $VALE_WARNINGS ]; then minWarnings=warning; else minWarnings=error; fi; if command -v vale > /dev/null 2>&1; then if ! vale --config .vale.ini --minAlertLevel $minWarnings {files}; then echo "ERROR: Fix any linting errors and make sure you are using the latest version of Vale."; exit 1; fi; else echo "ERROR: Vale not found. For more information, see https://vale.sh/docs/vale-cli/installation/."; exit 1; fi'
 
 auto-fix:
   parallel: true
