Add latest changes from gitlab-org/gitlab@master
[skip secret push protection]

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -63,6 +63,11 @@ pre-push:
       files: git diff --name-only --diff-filter=d $(git merge-base origin/master HEAD)..HEAD
       glob: '{,ee/}app/graphql/*.rb'
       run: bundle exec rake gitlab:graphql:check_docs
+    graphql_introspection_check:
+      tags: graphql schema backend
+      files: git diff --name-only --diff-filter=d $(git merge-base origin/master HEAD)..HEAD
+      glob: '{,ee/}app/graphql/**/*.rb'
+      run: bundle exec rake gitlab:graphql:check_introspection_sync
     openapi_docs:
       tags: documentation
       files: git diff --name-only --diff-filter=d $(git merge-base origin/master HEAD)..HEAD
@@ -220,6 +225,14 @@ pre-commit:
       files: git diff --name-only --diff-filter=d $(git merge-base origin/master HEAD) --cached
       glob: 'config/gitlab_loose_foreign_keys.yml'
       run: scripts/validate_loose_foreign_keys_ordering
+    prevent_graphql_schema_deletion:
+      tags: graphql schema
+      run: |
+        if git diff --cached --name-only --diff-filter=D | grep -q "public/-/graphql/introspection_result.json"; then
+          echo "🚫 Cannot delete GraphQL introspection schema file!"
+          echo "Regenerate it with: bundle exec rake gitlab:graphql:generate_introspection_schema"
+          exit 1
+        fi
     vale: # Requires Vale: https://docs.gitlab.com/development/documentation/testing/vale/
       tags: documentation style
       files: git diff --name-only --diff-filter=d --staged
