Add latest changes from gitlab-org/gitlab@master

diff --git a/.gitlab/ci/review-apps/qa.gitlab-ci.yml b/.gitlab/ci/review-apps/qa.gitlab-ci.yml
--- a/.gitlab/ci/review-apps/qa.gitlab-ci.yml
+++ b/.gitlab/ci/review-apps/qa.gitlab-ci.yml
@@ -52,6 +52,7 @@ include:
         --tag ~skip_signup_disabled \
         --tag ~requires_git_protocol_v2 \
         --tag ~requires_praefect \
+        --tag ~sanity_feature_flags \
         --force-color \
         --order random \
         --format documentation \
@@ -98,6 +99,29 @@ download-knapsack-report:
     paths:
       - qa/knapsack/review-qa-*.json
     expire_in: 1 day
+
+review-qa-sanity:
+  extends:
+    - .review-qa-base
+    - .review:rules:review-qa-sanity
+  retry: 1
+  variables:
+    QA_RUN_TYPE: review-qa-sanity
+  script:
+    - qa_run_status=0
+    - |
+      bundle exec rake "knapsack:rspec[\
+        --tag sanity_feature_flags \
+        --force-color \
+        --order random \
+        --format documentation \
+        --format RspecJunitFormatter --out tmp/rspec.xml \
+      ]" || qa_run_status=$?
+    - if [ ${qa_run_status} -ne 0 ]; then
+        release_sha=$(echo "${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA:-${CI_COMMIT_SHA}}" | cut -c1-11);
+        echo "Errors can be found at https://sentry.gitlab.net/gitlab/gitlab-review-apps/releases/${release_sha}/all-events/.";
+      fi
+    - exit ${qa_run_status}
 
 review-qa-smoke:
   extends:
