Add latest changes from gitlab-org/gitlab@14-8-stable-ee

diff --git a/.gitlab/ci/review-apps/qa.gitlab-ci.yml b/.gitlab/ci/review-apps/qa.gitlab-ci.yml
--- a/.gitlab/ci/review-apps/qa.gitlab-ci.yml
+++ b/.gitlab/ci/review-apps/qa.gitlab-ci.yml
@@ -27,11 +27,13 @@
     - echo "${CI_ENVIRONMENT_URL}"
     - cd qa
   script:
-    - |
-      bin/test "${QA_SCENARIO}" "${CI_ENVIRONMENT_URL}" \
-        -- \
-        --color --format documentation \
-        --format RspecJunitFormatter --out tmp/rspec.xml
+    - qa_run_status=0
+    - bin/test "${QA_SCENARIO}" "${CI_ENVIRONMENT_URL}" -- --color --format documentation --format RspecJunitFormatter --out tmp/rspec.xml || qa_run_status=$?
+    - if [ ${qa_run_status} -ne 0 ]; then
+        release_sha=$(echo "${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA:-${CI_COMMIT_SHA}}" | cut -c1-11);
+        echo "Errors can be found at https://sentry.gitlab.net/gitlab/gitlab-review-apps/releases/${release_sha}/all-events/.";
+      fi
+    - exit ${qa_run_status}
   artifacts:
     paths:
       - qa/tmp
diff --git a/scripts/rspec_bisect_flaky b/scripts/rspec_bisect_flaky
--- a/scripts/rspec_bisect_flaky
+++ b/scripts/rspec_bisect_flaky
@@ -10,20 +10,20 @@ if [ $# -eq 0 ]; then
   exit
 fi
 
-files=( $@ )
+files=( "$@" )
 len=${#files[@]}
 target=${files[$len-1]}
 
 # Trap interrupts and exit instead of continuing the loop
 trap "echo Exited!; exit 2;" SIGINT SIGTERM
 
-# Show which set of specs are running
-set -x
+# Show which set of specs are running and exit immediately if they fail.
+set -xe
 
 # Do the speedy case first, run each spec with our failing spec
 for file in "${files[@]}"; do
-  bin/rspec $file $target
+  bin/rspec "$file" "$target"
 done
 
 # Do a full bisect given we did not find candidates with speedy cases 
-bin/rspec --bisect=verbose $@
+bin/rspec --bisect=verbose "$@"
