Add latest changes from gitlab-org/gitlab@18-3-stable-ee

diff --git a/.gitlab/ci/rails.gitlab-ci.yml b/.gitlab/ci/rails.gitlab-ci.yml
--- a/.gitlab/ci/rails.gitlab-ci.yml
+++ b/.gitlab/ci/rails.gitlab-ci.yml
@@ -16,23 +16,14 @@ setup-test-env:
     - .rails:rules:setup-test-env
   stage: prepare
   needs:
+    - job: cache:workhorse-hash
     - job: cache:ruby-gems
       optional: true
   variables:
     SETUP_DB: "false"
   script:
-    - |
-      function setup_test_env() {
-        echo $CI_MERGE_REQUEST_APPROVED
-        source scripts/gitlab_component_helpers.sh
-        download_and_extract_gitlab_workhorse_package || true
-        section_start "setup-test-env" "Setting up testing environment"; scripts/setup-test-env; section_end "setup-test-env";
-        select_gitlab_workhorse_essentials
-        section_start "gitaly-test-build" "Compiling Gitaly binaries"; scripts/gitaly-test-build; section_end "gitaly-test-build";  # Do not use 'bundle exec' here
-        strip_executable_binaries "${TMP_TEST_FOLDER}"
-      }
-
-      run_with_custom_exit_code setup_test_env
+    - source scripts/gitlab_component_helpers.sh
+    - setup_test_env
   artifacts:
     expire_in: 7d
     paths:
@@ -54,7 +45,7 @@ setup-test-env:
       - ${TMP_TEST_FOLDER}/gitlab-test.bundle
       - ${TMP_TEST_FOLDER}/repositories/
       - ${TMP_TEST_FOLDER}/second_storage/
-      - ${TMP_TEST_GITLAB_WORKHORSE_PATH}/
+      - ${TMP_TEST_FOLDER}/gitlab-workhorse
       - ${TMP_TEST_FOLDER}/openbao/bin/
       - log/*.log
     when: always
@@ -67,34 +58,6 @@ setup-test-env-fips:
   variables:
     BUILD_OS: "ubi"
     OS_VERSION: ${UBI_VERSION}
-
-update-setup-test-env-cache:
-  extends:
-    - setup-test-env
-    - .setup-test-env-cache-push
-    - .shared:rules:update-cache
-  artifacts:
-    paths: []  # This job's purpose is only to update the cache.
-
-update-setup-test-env-cache-fips:
-  extends:
-    - setup-test-env-fips
-    - .setup-test-env-cache-push
-    - .shared:rules:update-cache
-
-update-gitaly-binaries-cache:
-  extends:
-    - setup-test-env
-    - .gitaly-binaries-cache-push
-    - .shared:rules:update-gitaly-binaries-cache
-  artifacts:
-    paths: []  # This job's purpose is only to update the cache.
-
-update-gitaly-binaries-cache-fips:
-  extends:
-    - setup-test-env-fips
-    - .gitaly-binaries-cache-push
-    - .shared:rules:update-gitaly-binaries-cache
 
 # Used in:
 #   - rspec:coverage
@@ -620,6 +583,9 @@ rspec:coverage:
       optional: true
   script:
     - run_with_custom_exit_code bundle exec scripts/merge-simplecov
+    - 'echo "coverage.xml size before stripping whitespace: $(cat coverage/coverage.xml | wc -c | numfmt --to=si --padding=1)"'
+    - sed -i -E 's/^ +//' coverage/coverage.xml
+    - 'echo "coverage.xml size after stripping whitespace: $(cat coverage/coverage.xml | wc -c | numfmt --to=si --padding=1)"'
   coverage: '/LOC \((\d+\.\d+%)\) covered.$/'
   artifacts:
     name: coverage
@@ -683,9 +649,9 @@ rspec:schedule-weekly-report-failures:
   when: on_failure
   script:
     - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
-      (scripts/slack g_global_search_alerts "☠️ \`${CI_JOB_NAME}\` weekly testing pipeline failed! ☠️ See ${CI_JOB_URL}" ci_failing "GitLab Bot" && exit 1);
+        (scripts/slack g_global_search_alerts "☠️ \`${CI_JOB_NAME}\` weekly testing pipeline failed! ☠️ See ${CI_JOB_URL}" ci_failing "GitLab Bot" && exit 1);
       else
-      echo "☠️ \`${CI_JOB_NAME}\` weekly testing pipeline failed! ☠️ See ${CI_JOB_URL}"
+        (echo "☠️ \`${CI_JOB_NAME}\` weekly testing pipeline failed! ☠️ See ${CI_JOB_URL}");
       fi
 
 rspec:flaky-tests-report:
@@ -741,29 +707,29 @@ rspec-predictive:pipeline-generate:
   script:
     - |
       scripts/generate_rspec_pipeline.rb \
-        -t "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}" \
+        -t "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}" \
         -k "${KNAPSACK_RSPEC_SUITE_REPORT_PATH}" \
-        -f "${RSPEC_MATCHING_TESTS_FOSS_PATH}" \
+        -f "${GLCI_PREDICTIVE_RSPEC_MATCHING_TESTS_FOSS_PATH}" \
         -j "${DEFAULT_RSPEC_PREDICTIVE_JOB_TAGS}" \
-        -o "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}.yml"
+        -o "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}.yml"
     - |
       scripts/generate_rspec_pipeline.rb \
-        -t "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}" \
+        -t "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}" \
         -k "${KNAPSACK_RSPEC_SUITE_REPORT_PATH}" \
-        -f "${RSPEC_MATCHING_TESTS_EE_PATH}" \
+        -f "${GLCI_PREDICTIVE_RSPEC_MATCHING_TESTS_EE_PATH}" \
         -j "${DEFAULT_RSPEC_PREDICTIVE_JOB_TAGS}" \
-        -o "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}-ee.yml" \
+        -o "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}-ee.yml" \
         -p "ee/"
-    - echo "Content of ${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}.yml:"
-    - cat "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}.yml"
+    - echo "Content of ${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}.yml:"
+    - cat "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}.yml"
     - echo "\n================================================\n"
-    - echo "Content of ${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}-ee.yml:"
-    - cat "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}-ee.yml"
+    - echo "Content of ${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}-ee.yml:"
+    - cat "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}-ee.yml"
   artifacts:
     expire_in: 1 day
     paths:
-      - "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}.yml"
-      - "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}-ee.yml"
+      - "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}.yml"
+      - "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}-ee.yml"
 
 rspec:predictive:trigger:
   extends:
@@ -788,7 +754,7 @@ rspec:predictive:trigger:
       yaml_variables: true
       pipeline_variables: true
     include:
-      - artifact: "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}.yml"
+      - artifact: "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}.yml"
         job: rspec-predictive:pipeline-generate
 
 rspec:predictive:trigger single-db:
@@ -811,7 +777,7 @@ rspec-ee:predictive:trigger:
   extends: rspec:predictive:trigger
   trigger:
     include:
-      - artifact: "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}-ee.yml"
+      - artifact: "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}-ee.yml"
         job: rspec-predictive:pipeline-generate
   variables:
     PIPELINE_NAME: 'rspec-ee:predictive'
@@ -820,7 +786,7 @@ rspec-ee:predictive:trigger single-db:
   extends: rspec:predictive:trigger single-db
   trigger:
     include:
-      - artifact: "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}-ee.yml"
+      - artifact: "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}-ee.yml"
         job: rspec-predictive:pipeline-generate
   variables:
     PIPELINE_NAME: 'rspec-ee:predictive single-db'
@@ -829,7 +795,7 @@ rspec-ee:predictive:trigger single-db-ci-connection:
   extends: rspec:predictive:trigger single-db-ci-connection
   trigger:
     include:
-      - artifact: "${RSPEC_PREDICTIVE_PIPELINE_TEMPLATE_YML}-ee.yml"
+      - artifact: "${GLCI_PREDICTIVE_RSPEC_PIPELINE_TEMPLATE_YML}-ee.yml"
         job: rspec-predictive:pipeline-generate
   variables:
     PIPELINE_NAME: 'rspec-ee:predictive single-db-ci-connection'
@@ -1346,14 +1312,14 @@ rspec fail-fast:
     - .rspec-base-pg16
     - .rspec-fail-fast  # extends from .rspec-fail-fast last to override script from .rspec-base-pg16
   variables:
-    MATCHING_TESTS_PATH: "${RSPEC_MATCHING_TESTS_FOSS_PATH}"
+    MATCHING_TESTS_PATH: "${GLCI_PREDICTIVE_RSPEC_MATCHING_TESTS_FOSS_PATH}"
 
 rspec-ee fail-fast:
   extends:
     - .rspec-ee-base-pg16
     - .rspec-fail-fast  # extends from .rspec-fail-fast last to override script from .rspec-ee-base-pg16
   variables:
-    MATCHING_TESTS_PATH: "${RSPEC_MATCHING_TESTS_EE_PATH}"
+    MATCHING_TESTS_PATH: "${GLCI_PREDICTIVE_RSPEC_MATCHING_TESTS_EE_PATH}"
 
 fail-pipeline-early:
   extends:
