Add latest changes from gitlab-org/gitlab@17-0-stable-ee

diff --git a/.gitlab/ci/static-analysis.gitlab-ci.yml b/.gitlab/ci/static-analysis.gitlab-ci.yml
--- a/.gitlab/ci/static-analysis.gitlab-ci.yml
+++ b/.gitlab/ci/static-analysis.gitlab-ci.yml
@@ -108,7 +108,7 @@ rubocop:
   script:
     - |
       # For non-merge request, or when RUN_ALL_RUBOCOP is 'true', run all RuboCop rules
-      if [ -z "${CI_MERGE_REQUEST_IID}" ] || [ "${RUN_ALL_RUBOCOP}" == "true" ]; then
+      if [ -z "${CI_MERGE_REQUEST_IID:-$FIND_CHANGES_MERGE_REQUEST_IID}" ] || [ "${RUN_ALL_RUBOCOP}" == "true" ]; then
         # Silence cop offenses for rules with "grace period".
         # We won't notify Slack if offenses were silenced to avoid frequent messages.
         # Job `update-static-analysis-cache` takes care of Slack notifications every 2 hours.
@@ -172,20 +172,22 @@ semgrep-appsec-custom-rules:
   image: returntocorp/semgrep
   needs: []
   script:
-    # Required to avoid a timeout https://github.com/returntocorp/semgrep/issues/5395
     - git fetch origin master
     - git clone $CUSTOM_RULES_REPOSITORY "${CI_BUILDS_DIR}/sast-custom-rules"
     # Include/exclude list isn't ideal https://github.com/returntocorp/semgrep/issues/5399
     - |
-      semgrep ci --gitlab-sast --metrics off --config "${CI_BUILDS_DIR}/sast-custom-rules" \
+      rm "${CI_BUILDS_DIR}/sast-custom-rules/.gitlab-ci.yml" # semgrep fails when there are yaml files that are not rules
+      semgrep ci --metrics off --config "${CI_BUILDS_DIR}/sast-custom-rules" \
         --include app --include lib --include workhorse \
-        --exclude '*_test.go' --exclude spec --exclude qa --exclude tooling > gl-sast-report.json || true
+        --exclude '*_test.go' --exclude spec --exclude qa --exclude tooling --json --verbose > gl-sast-report.json || true
+
   variables:
-    CUSTOM_RULES_REPOSITORY: https://gitlab.com/gitlab-com/gl-security/appsec/sast-custom-rules.git
+    CUSTOM_RULES_REPOSITORY: https://gitlab.com/gitlab-com/gl-security/product-security/appsec/sast-custom-rules.git
   artifacts:
     expire_in: 30 days
     paths:
       - gl-sast-report.json
+    access: 'developer'
 
 audit-event-types-verify:
   variables:
@@ -200,19 +202,46 @@ audit-event-types-verify:
   script:
     - bundle exec rake gitlab:audit_event_types:check_docs
 
+custom-roles-verify:
+  variables:
+    SETUP_DB: "false"
+  extends:
+    - .default-retry
+    - .ruby-cache
+    - .default-before_script
+    - .custom-roles:rules:custom-roles-verify
+  stage: lint
+  needs: []
+  script:
+    - bundle exec rake gitlab:custom_roles:check_docs
+
+templates-shellcheck:
+  extends:
+    - .ci-templates:rules:shellcheck
+    - .default-before_script
+    - .default-retry
+    - .ruby-cache
+    - .use-pg16
+  stage: lint
+  needs:
+    - setup-test-env
+  script:
+    - bundle exec scripts/lint_templates_bash.rb
+
 ping-appsec-for-sast-findings:
   stage: lint
   image: alpine:latest
   extends:
     - .ping-appsec-for-sast-findings:rules
   variables:
-    # Project Access Token bot ID for /gitlab-com/gl-security/appsec/sast-custom-rules
-    BOT_USER_ID: 14406065
+    # Project Access Token bot ID for /gitlab-com/gl-security/product-security/appsec/sast-custom-rules
+    BOT_USER_ID: 19650678
   needs:
     - semgrep-appsec-custom-rules
   script:
-    - apk add jq curl
-    - scripts/process_custom_semgrep_results.sh
+    - apk update
+    - apk add ruby
+    - ruby scripts/process_custom_semgrep_results.rb
 
 trigger-depsaster:
   extends: .static-analysis:rules:trigger-depsaster
@@ -221,7 +250,7 @@ trigger-depsaster:
     MERGE_REQUEST_PROJECT_ID: $CI_MERGE_REQUEST_PROJECT_ID
     MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
   trigger:
-    project: "gitlab-com/gl-security/appsec/tooling/depsaster"
+    project: "gitlab-com/gl-security/product-security/appsec/tooling/depsaster"
   allow_failure: true
 
 ping-appsec-for-dependency-review:
@@ -232,7 +261,7 @@ ping-appsec-for-dependency-review:
     DISABLE_MENTIONS: "false"
     DISABLE_SCORING: "true"
     DISABLE_COMMENTING: "false"
-    DEPENDENCY_REVIEW_BOT_CI_REG: "${CI_REGISTRY}/gitlab-com/gl-security/appsec/tooling/depscore/master"
+    DEPENDENCY_REVIEW_BOT_CI_REG: "${CI_REGISTRY}/gitlab-com/gl-security/product-security/appsec/tooling/depscore/master"
   extends: [".ping-appsec-for-dependency-review:rules", ".use-docker-in-docker"]
   before_script:
     - apk add jq curl
diff --git a/scripts/validate-monorepo-gem b/scripts/validate-monorepo-gem
--- a/scripts/validate-monorepo-gem
+++ b/scripts/validate-monorepo-gem
@@ -1,17 +1,57 @@
 #!/bin/bash
 
-if [[ $# -ne 1 ]]; then
-  echo "usage: $0 <gem-name>"
+set -euo pipefail
+
+OWNER_HANDLE="gitlab_rubygems"
+
+error() {
+  echo "ERROR:" "$@"
   exit 1
+}
+
+warn() {
+  echo "WARNING:" "$@"
+}
+
+validate_gem() {
+  validate_existence "$1"
+  validate_owners "$1"
+  validate_content "$1"
+}
+
+validate_existence() {
+  if gem specification --quiet --silent --remote --ruby "$1"; then
+    return 0
+  fi
+
+  if gem specification --quiet --silent --remote --ruby --pre "$1"; then
+    return 0
+  fi
+
+  error "The '$1' is missing. Push stub gem to RubyGems with version 0.0.0. See https://docs.gitlab.com/ee/development/gems.html#reserve-a-gem-name"
+}
+
+validate_owners() {
+  if ! curl --silent --fail "https://rubygems.org/api/v1/gems/$1/owners.json" | grep --silent "\"handle\":\"$OWNER_HANDLE\""; then
+    error "Gem '$1' does not contain '$OWNER_HANDLE' as owner."
+  fi
+}
+
+validate_content() {
+  local tmpdir
+  tmpdir=$(mktemp --directory)
+  gem unpack "$1" --quiet --silent --target "$tmpdir"
+
+  if ! grep --silent --recursive --perl-regexp '^\s*raise "Reserved for GitLab"$' "$tmpdir"; then
+    warn "Contents of gem '$1' does not contain 'raise \"Reserved for GitLab\"'."
+  fi
+}
+
+if [[ $# -ne 1 ]]; then
+  error "usage: $0 <gem-name>"
 fi
 
-if gem specification --remote --ruby "$1"; then
-  exit 0
-fi
+echo "Validating gem '$1'"
 
-if gem specification --remote --ruby --pre "$1"; then
-  exit 0
-fi
-
-echo "The '$1' is missing. Push stub gem to RubyGems with version 0.0.1."
-exit 1
+validate_gem "$1"
+echo "SUCCESS!"
